### PR TITLE
Add a change listener to the component

### PR DESCRIPTION
**Pull request by jcgueriaud1**
Currently the value is changed on blur.
In my Vaadin application, I would like to trigger the change event earlier.
So this PR is adding a new event AceChanged that listens the event sent in this PR: https://github.com/F0rce/lit-ace/pull/3

You need to bump the version of the web component.

### CODE REVIEW

**Comment by F0rce** [comment]
Hello @jcgueriaud1,

first of all thanks for contributing :)

But unfortunately, I will not implement the listener, because of a glitch that was causing the mouse cursor to jump at the end of the editor (https://github.com/Sergio70/AceEditorV14/issues/7) - this was happening in the old version of the ace editor before I was starting contributing to it... so I had to find a workaround, which is the blur event.

Could you please try to type really fast in your version of ace and lit-ace and let me know if the glitch is still persistant ? (because ace itself hasn't received any updates since 12 months i think). If not I will go for a further investigation.

Thanks,
David

**Comment by jcgueriaud1** [comment]
Hi, I've created an example and try it. It's working fine.

It's a new event that does "nothing" if you don't listen it. It doesn't refresh the value.

In my use case, it's basically to enable a save button when the user starts to type instead of waiting for the blur event.

**Review by F0rce — APPROVED** [review]
After multiple and increased testing, the changes are suitable for a new release

**Comment by F0rce** [comment]
@jcgueriaud1 https://vaadin.com/directory/component/ace/1.3.3 

Have a great Weekend and thanks for implementing :)

**Comment by jcgueriaud1** [comment]
Thanks a lot for the fast release 👍

**Pull request merged**
